name: pomoflev
description: PomoFlev - Pomodoro Timer made by FARSI Ayman using Flutter
homepage: https://github.com/AymanFARSI/PomoFleV
version: 0.2.1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_manager: ^0.2.3
  get: ^4.6.3
  flutter_secure_storage: ^5.0.2
  fluent_ui: ^3.12.0
  yaru: ^0.3.2
  system_theme: ^2.0.0
  audioplayers: ^1.0.0-rc.4
  overlay_support: ^2.0.0
  tray_manager: ^0.1.7
  about: ^2.1.1
  icons_launcher: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.6.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/notif_sounds/
    - assets/logos/

msix_config:
  display_name: PomoFleV
  publisher_display_name: FARSI Ayman
  identity_name: com.evildave.pomoflev
  msix_version: 0.1.0.0
  # logo_path: assets/logos/pomoflev_logo.png

flutter_icons:
  image_path: 'assets/logos/pomoflev_logo.png'
  ios: true
  android: true
  windows: true
  linux: true
  macos: true
  web: true
  remove_alpha_ios: true